{
  "summary": {
    "outcome": "Failed",
    "testsRan": 1,
    "passing": 0,
    "failing": 1,
    "skipped": 0,
    "passRate": "0%",
    "failRate": "100%",
    "skipRate": "0%",
    "testStartTime": "Thu Apr 13 2023 16:17:36",
    "testExecutionTimeInMs": 39,
    "testTotalTimeInMs": 39,
    "commandTimeInMs": 139,
    "hostname": "https://d8d0000090l4eeaq-dev-ed.develop.my.salesforce.com",
    "orgId": "00D8d0000090l4EEAQ",
    "username": "ridvansaman34@gmail.com",
    "testRunId": "7078d000039dqRJ",
    "userId": "0058d000005gLuVAAU"
  },
  "tests": [
    {
      "id": "07M8d000002Jt0MEAS",
      "queueItemId": "7098d000000V0XYAA0",
      "stackTrace": "Class.CalculatorTest.testAddThreeNumbers: line 51, column 1",
      "message": "System.AssertException: Assertion Failed: Unexpected result for adding three numbers: Expected: 50, Actual: 60",
      "asyncApexJobId": "7078d000039dqRJAAY",
      "methodName": "testAddThreeNumbers",
      "outcome": "Fail",
      "apexLogId": "07L8d000006KgpmEAC",
      "apexClass": {
        "id": "01p8d00000QwvGoAAJ",
        "name": "CalculatorTest",
        "namespacePrefix": null,
        "fullName": "CalculatorTest"
      },
      "runTime": 39,
      "testTimestamp": "2023-04-13T15:17:36.000+0000",
      "fullName": "CalculatorTest.testAddThreeNumbers",
      "diagnostic": {
        "exceptionMessage": "System.AssertException: Assertion Failed: Unexpected result for adding three numbers: Expected: 50, Actual: 60",
        "exceptionStackTrace": "Class.CalculatorTest.testAddThreeNumbers: line 51, column 1",
        "className": "CalculatorTest",
        "compileProblem": "",
        "lineNumber": 51,
        "columnNumber": 1
      }
    }
  ]
}